name: Fieldbases
description: 'Field configuration for multiple paragraph types'
type: module
core: 8.x
dependencies:
  - content_moderation
  - entity_reference_revisions
  - field
  - file
  - image
  - link
  - paragraphs
  - text
  - video_embed_field
version: 8.x-1.0
package: 'Shared configuration'
